const copy = {
  es: {
    navLinux:"Linux",navModules:"Módulos",navModes:"Modos",navLibrary:"Biblioteca",
    heroEyebrow:"VERBO DESKTOP",heroTitle:"Tus módulos ya no pertenecen a un sistema operativo.",heroLead:"Verbo reúne módulos compatibles de e-Sword, MySword y Verbo en una sola aplicación de escritorio para Linux, macOS y Windows.",download:"Descargar Verbo",discover:"Ver cómo funciona",heroMicro:"Linux disponible ahora. macOS y Windows llegarán próximamente.",soon:"Próximamente",
    linuxEyebrow:"LINUX NATIVO",linuxTitle:"Linux ya tenía software bíblico. Ahora puede tener la biblioteca.",linuxBody:"Importa módulos compatibles procedentes de ecosistemas de Windows y Android y utilízalos directamente en Verbo, sin tener que ejecutar la aplicación dentro de Windows.",linuxFact1Title:"Nativo",linuxFact1Text:"Pensado para ejecutarse directamente en Linux.",linuxFact2Title:"Tu colección",linuxFact2Text:"Aprovecha módulos compatibles que ya utilizabas.",linuxFact3Title:"Un solo entorno",linuxFact3Text:"Estudio, enseñanza y biblioteca en la misma aplicación.",
    ecoEyebrow:"UNA BIBLIOTECA, VARIOS ECOSISTEMAS",ecoTitle:"Lo que antes vivía separado puede reunirse en Verbo.",ecoBody:"Módulos compatibles de e-Sword, MySword y Verbo pueden converger en una sola biblioteca y viajar contigo entre plataformas.",
    platformEyebrow:"TRES PLATAFORMAS",platformTitle:"Una experiencia de escritorio real.",platformLinux:"La prioridad del lanzamiento: una biblioteca bíblica amplia en un entorno Linux nativo.",platformMac:"Importa tus recursos y trabaja en Verbo directamente desde tu Mac.",platformWindows:"Una nueva alternativa para reunir recursos, estudio y preparación en un solo entorno.",
    modesEyebrow:"TRES FORMAS DE TRABAJAR",modesTitle:"Estudia. Prepara. Lee.",modesBody:"Verbo no es solo un importador. La aplicación cambia de espacio según lo que necesitas hacer.",studyTitle:"Modo Estudio",studyText:"Biblia, referencias cruzadas, idiomas bíblicos, Strong y recursos alrededor del texto.",teachTitle:"Preparación de enseñanza",teachText:"Editor, Biblia y herramientas de estudio trabajando juntos para bosquejos, clases y predicaciones.",libraryTitle:"Modo Biblioteca",libraryText:"Lee y organiza libros, historia, devocionales y otros recursos en una biblioteca visual.",
    toolsEyebrow:"HERRAMIENTAS DE ESTUDIO",toolsTitle:"Mucho más que abrir una Biblia.",toolsBody:"Recursos visuales, lingüísticos, históricos y personales permanecen cerca del texto.",mapsTitle:"Mapas bíblicos",mapsText:"Historia y geografía en ventanas de consulta.",strongTitle:"Strong y notas",strongText:"Idiomas bíblicos, diccionarios y tus propias notas.",customsTitle:"Costumbres y tradiciones",customsText:"Contexto cultural disponible mientras estudias.",
    libraryEyebrow:"TU BIBLIOTECA PERSONAL",librarySectionTitle:"De los Padres Apostólicos a tus próximos recursos.",librarySectionBody:"Verbo también es un espacio de lectura. Libros, historia, devocionales, Padres Apostólicos y otros recursos pueden convivir con tu estudio bíblico.",libItem1:"Padres Apostólicos",libItem2:"Historia y contexto",libItem3:"Devocionales y libros",libItem4:"Recursos importados por el usuario",
    navFathers:"Padres Apostólicos",
    padresEyebrow:"TUS PRIMEROS MÓDULOS",padresTitle:"Descarga tus primeros módulos de los Padres Apostólicos en español",padresBody:"Nueve obras, una por autor, traducidas por Verbo y listas para importar: el texto completo y sus fragmentos anclados a los versículos que citan, igual que en la Biblia web. Con Verbo Desktop instalado, \"Abrir en Verbo Desktop\" los importa solo.",
    padresOpenBtn:"Abrir en Verbo Desktop",padresZipBtn:"Descargar .zip",padresNoApp:"¿No tenés la app? Descargala más abajo.",
    padresIreneoTitle:"Ireneo de Lyon — Contra las Herejías",padresClementeTitle:"Clemente de Roma — 1 y 2 Clemente",padresPolicarpoTitle:"Policarpo de Esmirna",padresIgnacioTitle:"Ignacio de Antioquía — El Martirio",padresDidacheTitle:"La Didaché",padresBernabeTitle:"Epístola de Bernabé",padresDiognetoTitle:"Epístola a Diogneto",padresHermasTitle:"El Pastor de Hermas",padresPapiasTitle:"Papías de Hierápolis",
    padresIreneoPeriod:"Año ~180 d.C.",padresIreneoDesc:"Contra las Herejías — refuta el gnosticismo y defiende la fe apostólica.",padresClementePeriod:"Años 96–140 d.C.",padresClementeDesc:"1 y 2 Clemente — la carta más antigua fuera del Nuevo Testamento y la homilía cristiana más antigua conservada.",padresPolicarpoPeriod:"Años 110–160 d.C.",padresPolicarpoDesc:"A los Filipenses y su Martirio — discípulo del apóstol Juan, y el relato de su muerte en la hoguera.",padresIgnacioPeriod:"Año ~108 d.C.",padresIgnacioDesc:"El Martirio — el viaje de Ignacio de Antioquía hacia su muerte en Roma.",padresDidachePeriod:"Años 50–120 d.C.",padresDidacheDesc:"Enseñanza de los Doce Apóstoles — manual antiguo de ética, bautismo y eucaristía.",padresBernabePeriod:"Años 70–135 d.C.",padresBernabeDesc:"Interpretación cristiana del Antiguo Testamento y enseñanza moral.",padresDiognetoPeriod:"Años 130–200 d.C.",padresDiognetoDesc:"Defensa temprana de la fe cristiana dirigida a un lector pagano culto.",padresHermasPeriod:"Años 90–150 d.C.",padresHermasDesc:"Visiones y parábolas sobre el arrepentimiento, muy leída en la iglesia primitiva.",padresPapiasPeriod:"Años 110–140 d.C.",padresPapiasDesc:"Fragmentos citados por autores posteriores, con testimonios tempranos sobre los evangelios.",
    downloadEyebrow:"VERBO DESKTOP",downloadTitle:"Tu biblioteca. Tu sistema. Tu espacio de estudio.",downloadBody:"Paquetes de Linux disponibles (.deb y .rpm, versión de desarrollo). macOS y Windows llegarán próximamente.",footer:"Estudio bíblico de escritorio.",
    reportLabel:"¿Encontraste un error? Cuéntanoslo.",reportPlaceholder:"Describe brevemente el problema que encontraste...",reportSend:"Enviar reporte"
  },
  en: {
    navLinux:"Linux",navModules:"Modules",navModes:"Modes",navLibrary:"Library",
    heroEyebrow:"VERBO DESKTOP",heroTitle:"Your modules no longer belong to an operating system.",heroLead:"Verbo brings compatible e-Sword, MySword and Verbo modules together in one desktop application for Linux, macOS and Windows.",download:"Download Verbo",discover:"See how it works",heroMicro:"Linux available now. macOS and Windows are coming soon.",soon:"Coming soon",
    linuxEyebrow:"NATIVE ON LINUX",linuxTitle:"Linux already had Bible software. Now it can have the library.",linuxBody:"Import compatible modules from Windows and Android ecosystems and use them directly in Verbo, without having to run the application inside Windows.",linuxFact1Title:"Native",linuxFact1Text:"Built to run directly on Linux.",linuxFact2Title:"Your collection",linuxFact2Text:"Keep using compatible modules you already know.",linuxFact3Title:"One workspace",linuxFact3Text:"Study, teaching preparation and library in the same app.",
    ecoEyebrow:"ONE LIBRARY, MULTIPLE ECOSYSTEMS",ecoTitle:"What used to live apart can come together in Verbo.",ecoBody:"Compatible e-Sword, MySword and Verbo modules can converge in one library and travel with you across platforms.",
    platformEyebrow:"THREE PLATFORMS",platformTitle:"A true desktop experience.",platformLinux:"The launch priority: a broad Bible library in a native Linux environment.",platformMac:"Import your resources and work in Verbo directly from your Mac.",platformWindows:"A new alternative for bringing resources, study and preparation into one workspace.",
    modesEyebrow:"THREE WAYS TO WORK",modesTitle:"Study. Prepare. Read.",modesBody:"Verbo is more than an importer. The workspace changes with the job you need to do.",studyTitle:"Study Mode",studyText:"Bible text, cross-references, biblical languages, Strong and resources around the passage.",teachTitle:"Teaching Preparation",teachText:"Editor, Bible and study tools working together for outlines, lessons and sermons.",libraryTitle:"Library Mode",libraryText:"Read and organize books, history, devotionals and other resources in a visual library.",
    toolsEyebrow:"STUDY TOOLS",toolsTitle:"Much more than opening a Bible.",toolsBody:"Visual, linguistic, historical and personal resources stay close to the text.",mapsTitle:"Biblical maps",mapsText:"History and geography in consultation windows.",strongTitle:"Strong and notes",strongText:"Biblical languages, dictionaries and your own notes.",customsTitle:"Customs and traditions",customsText:"Cultural context available while you study.",
    libraryEyebrow:"YOUR PERSONAL LIBRARY",librarySectionTitle:"From the Apostolic Fathers to the resources you add next.",librarySectionBody:"Verbo is also a reading space. Books, history, devotionals, Apostolic Fathers and other resources can live alongside your Bible study.",libItem1:"Apostolic Fathers",libItem2:"History and context",libItem3:"Devotionals and books",libItem4:"User-imported resources",
    navFathers:"Apostolic Fathers",
    padresEyebrow:"YOUR FIRST MODULES",padresTitle:"Download your first Apostolic Fathers modules in Spanish",padresBody:"Nine works, one per author, translated by Verbo and ready to import: the full text plus the verse-anchored fragments it cites, just like on the Verbo Bible website. With Verbo Desktop installed, \"Open in Verbo Desktop\" imports it for you.",
    padresOpenBtn:"Open in Verbo Desktop",padresZipBtn:"Download .zip",padresNoApp:"Don't have the app? Download it below.",
    padresIreneoTitle:"Irenaeus of Lyon — Against Heresies",padresClementeTitle:"Clement of Rome — 1 & 2 Clement",padresPolicarpoTitle:"Polycarp of Smyrna",padresIgnacioTitle:"Ignatius of Antioch — The Martyrdom",padresDidacheTitle:"The Didache",padresBernabeTitle:"Epistle of Barnabas",padresDiognetoTitle:"Epistle to Diognetus",padresHermasTitle:"The Shepherd of Hermas",padresPapiasTitle:"Papias of Hierapolis",
    padresIreneoPeriod:"c. AD 180",padresIreneoDesc:"Against Heresies — refutes Gnostic teaching and defends the apostolic faith.",padresClementePeriod:"AD 96–140",padresClementeDesc:"1 & 2 Clement — the oldest Christian letter outside the New Testament and the oldest surviving Christian homily.",padresPolicarpoPeriod:"AD 110–160",padresPolicarpoDesc:"To the Philippians and his Martyrdom — a disciple of the apostle John, and the account of his death at the stake.",padresIgnacioPeriod:"c. AD 108",padresIgnacioDesc:"The Martyrdom — Ignatius of Antioch's journey toward his death in Rome.",padresDidachePeriod:"AD 50–120",padresDidacheDesc:"Teaching of the Twelve Apostles — an early manual on ethics, baptism and the eucharist.",padresBernabePeriod:"AD 70–135",padresBernabeDesc:"A Christian reading of the Old Testament and moral teaching.",padresDiognetoPeriod:"AD 130–200",padresDiognetoDesc:"An early defense of the Christian faith addressed to an educated pagan reader.",padresHermasPeriod:"AD 90–150",padresHermasDesc:"Visions and parables about repentance, widely read in the early church.",padresPapiasPeriod:"AD 110–140",padresPapiasDesc:"Fragments quoted by later writers, with early testimony about the Gospels.",
    downloadEyebrow:"VERBO DESKTOP",downloadTitle:"Your library. Your system. Your study space.",downloadBody:"Linux packages available (.deb and .rpm, development build). macOS and Windows are coming soon.",footer:"Desktop Bible study.",
    reportLabel:"Found a bug? Let us know.",reportPlaceholder:"Briefly describe the issue you found...",reportSend:"Send report"
  },
  pt: {
    navLinux:"Linux",navModules:"Módulos",navModes:"Modos",navLibrary:"Biblioteca",
    heroEyebrow:"VERBO DESKTOP",heroTitle:"Seus módulos já não pertencem a um sistema operacional.",heroLead:"Verbo reúne módulos compatíveis de e-Sword, MySword e Verbo em um único aplicativo de desktop para Linux, macOS e Windows.",download:"Baixar Verbo",discover:"Ver como funciona",heroMicro:"Linux disponível agora. macOS e Windows chegarão em breve.",soon:"Em breve",
    linuxEyebrow:"NATIVO NO LINUX",linuxTitle:"O Linux já tinha software bíblico. Agora pode ter a biblioteca.",linuxBody:"Importe módulos compatíveis vindos dos ecossistemas Windows e Android e use-os diretamente no Verbo, sem precisar executar o aplicativo dentro do Windows.",linuxFact1Title:"Nativo",linuxFact1Text:"Feito para rodar diretamente no Linux.",linuxFact2Title:"Sua coleção",linuxFact2Text:"Aproveite módulos compatíveis que você já usava.",linuxFact3Title:"Um só ambiente",linuxFact3Text:"Estudo, preparação de ensino e biblioteca no mesmo aplicativo.",
    ecoEyebrow:"UMA BIBLIOTECA, VÁRIOS ECOSSISTEMAS",ecoTitle:"O que antes vivia separado pode se reunir no Verbo.",ecoBody:"Módulos compatíveis de e-Sword, MySword e Verbo podem convergir em uma única biblioteca e acompanhar você entre plataformas.",
    platformEyebrow:"TRÊS PLATAFORMAS",platformTitle:"Uma experiência real de desktop.",platformLinux:"A prioridade do lançamento: uma biblioteca bíblica ampla em um ambiente Linux nativo.",platformMac:"Importe seus recursos e trabalhe no Verbo diretamente no seu Mac.",platformWindows:"Uma nova alternativa para reunir recursos, estudo e preparação em um único ambiente.",
    modesEyebrow:"TRÊS FORMAS DE TRABALHAR",modesTitle:"Estude. Prepare. Leia.",modesBody:"Verbo não é apenas um importador. O espaço muda conforme o trabalho que você precisa fazer.",studyTitle:"Modo Estudo",studyText:"Bíblia, referências cruzadas, idiomas bíblicos, Strong e recursos ao redor do texto.",teachTitle:"Preparação de ensino",teachText:"Editor, Bíblia e ferramentas de estudo trabalhando juntos para esboços, aulas e pregações.",libraryTitle:"Modo Biblioteca",libraryText:"Leia e organize livros, história, devocionais e outros recursos em uma biblioteca visual.",
    toolsEyebrow:"FERRAMENTAS DE ESTUDO",toolsTitle:"Muito mais do que abrir uma Bíblia.",toolsBody:"Recursos visuais, linguísticos, históricos e pessoais permanecem perto do texto.",mapsTitle:"Mapas bíblicos",mapsText:"História e geografia em janelas de consulta.",strongTitle:"Strong e notas",strongText:"Idiomas bíblicos, dicionários e suas próprias notas.",customsTitle:"Costumes e tradições",customsText:"Contexto cultural disponível enquanto você estuda.",
    libraryEyebrow:"SUA BIBLIOTECA PESSOAL",librarySectionTitle:"Dos Pais Apostólicos aos próximos recursos que você adicionar.",librarySectionBody:"Verbo também é um espaço de leitura. Livros, história, devocionais, Pais Apostólicos e outros recursos podem conviver com seu estudo bíblico.",libItem1:"Pais Apostólicos",libItem2:"História e contexto",libItem3:"Devocionais e livros",libItem4:"Recursos importados pelo usuário",
    navFathers:"Pais Apostólicos",
    padresEyebrow:"SEUS PRIMEIROS MÓDULOS",padresTitle:"Baixe seus primeiros módulos dos Pais Apostólicos em espanhol",padresBody:"Nove obras, uma por autor, traduzidas pela Verbo e prontas para importar: o texto completo e seus fragmentos ligados aos versículos que citam, como na Bíblia web. Com o Verbo Desktop instalado, \"Abrir no Verbo Desktop\" importa sozinho.",
    padresOpenBtn:"Abrir no Verbo Desktop",padresZipBtn:"Baixar .zip",padresNoApp:"Não tem o app? Baixe mais abaixo.",
    padresIreneoTitle:"Ireneu de Lyon — Contra as Heresias",padresClementeTitle:"Clemente de Roma — 1 e 2 Clemente",padresPolicarpoTitle:"Policarpo de Esmirna",padresIgnacioTitle:"Inácio de Antioquia — O Martírio",padresDidacheTitle:"A Didaquê",padresBernabeTitle:"Epístola de Barnabé",padresDiognetoTitle:"Epístola a Diogneto",padresHermasTitle:"O Pastor de Hermas",padresPapiasTitle:"Papias de Hierápolis",
    padresIreneoPeriod:"Ano ~180 d.C.",padresIreneoDesc:"Contra as Heresias — refuta o gnosticismo e defende a fé apostólica.",padresClementePeriod:"Anos 96–140 d.C.",padresClementeDesc:"1 e 2 Clemente — a carta mais antiga fora do Novo Testamento e a homilia cristã mais antiga que se conhece.",padresPolicarpoPeriod:"Anos 110–160 d.C.",padresPolicarpoDesc:"Aos Filipenses e seu Martírio — discípulo do apóstolo João, e o relato de sua morte na fogueira.",padresIgnacioPeriod:"Ano ~108 d.C.",padresIgnacioDesc:"O Martírio — a jornada de Inácio de Antioquia rumo à sua morte em Roma.",padresDidachePeriod:"Anos 50–120 d.C.",padresDidacheDesc:"Ensino dos Doze Apóstolos — manual antigo de ética, batismo e eucaristia.",padresBernabePeriod:"Anos 70–135 d.C.",padresBernabeDesc:"Interpretação cristã do Antigo Testamento e ensino moral.",padresDiognetoPeriod:"Anos 130–200 d.C.",padresDiognetoDesc:"Defesa antiga da fé cristã dirigida a um leitor pagão culto.",padresHermasPeriod:"Anos 90–150 d.C.",padresHermasDesc:"Visões e parábolas sobre o arrependimento, muito lida na igreja primitiva.",padresPapiasPeriod:"Anos 110–140 d.C.",padresPapiasDesc:"Fragmentos citados por autores posteriores, com testemunhos antigos sobre os evangelhos.",
    downloadEyebrow:"VERBO DESKTOP",downloadTitle:"Sua biblioteca. Seu sistema. Seu espaço de estudo.",downloadBody:"Pacotes de Linux disponíveis (.deb e .rpm, versão de desenvolvimento). macOS e Windows chegarão em breve.",footer:"Estudo bíblico para desktop.",
    reportLabel:"Encontrou um erro? Conte pra gente.",reportPlaceholder:"Descreva brevemente o problema que você encontrou...",reportSend:"Enviar relatório"
  }
};
function setLang(lang){
  const dict=copy[lang]||copy.es;
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key]) el.textContent=dict[key]});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(dict[key]) el.placeholder=dict[key]});
  document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));
  localStorage.setItem('verboDesktopLang',lang);
}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setLang(btn.dataset.lang)));
const preferred=localStorage.getItem('verboDesktopLang') || (navigator.language||'es').slice(0,2);
setLang(['es','en','pt'].includes(preferred)?preferred:'es');
document.getElementById('year').textContent=new Date().getFullYear();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
// macOS/Windows todavía no tienen paquete — sus botones de descarga son
// solo un aviso de "Próximamente", no deben saltar al inicio de la página.
document.querySelectorAll('.is-soon').forEach(el=>el.addEventListener('click',e=>e.preventDefault()));
// Reporte de errores: sin backend propio, así que abre el cliente de correo
// del usuario con el reporte ya escrito en el cuerpo — nada de nombres,
// correos ni almacenamiento propio, solo lo que la persona escribió.
const reportForm=document.getElementById('reportForm');
if(reportForm){
  reportForm.addEventListener('submit',e=>{
    e.preventDefault();
    const text=document.getElementById('reportText').value.trim();
    if(!text) return;
    const subject=encodeURIComponent('Reporte de error - Verbo Desktop');
    const body=encodeURIComponent(text);
    window.location.href=`mailto:soporte@verbobiblia.com?subject=${subject}&body=${body}`;
  });
}
